Don't pass form data to email
UKHomeOfficeForms/hof-emailer pull request #13
Opened 2016-12-01 15:18 UTC by bendiggle

In email-service.js constructor only set this.data if includeInEmail is true other set as empty string. This is so that emails can be sent with out the form data being in the email

2016-12-01 16:18 UTC, joefitter requested changes

2016-12-01 16:18 UTC, joefitter commented on .idea/compiler.xml
> +</project>
@bendiggle 👎

2016-12-02 08:19 UTC, JoeChapman requested changes
what @joefitter said

2016-12-02 10:28 UTC, bendiggle commented
@JoeChapman It was updated way before your comment!! @joefitter

2016-12-13 08:18 UTC, JoeChapman approved these changes

2016-12-13 08:18 UTC, JoeChapman commented
@joefitter what say you?

2016-12-13 09:35 UTC, closed without merging